# Generated by Django 6.0.5 on 2026-06-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('1x8', 'CTO 1x8'), ('1x16', 'CTO 1x16')], max_length=10)),
                ('rua', models.CharField(max_length=200)),
                ('portas_total', models.IntegerField(default=8)),
                ('portas_ocupadas', models.IntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
    ]
