# Generated by Django 5.2.5 on 2026-06-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
