# Generated by Django 5.0.6 on 2026-07-24 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('tipo_pessoa', models.CharField(choices=[('fisica', 'Pessoa Física'), ('juridica', 'Pessoa Jurídica')], default='fisica', max_length=10)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('possui_whatsapp', models.BooleanField(default=True, verbose_name='Possui WhatsApp')),
                ('status', models.CharField(choices=[('ativo', 'Ativo em Dia'), ('inadimplente', 'Inadimplente'), ('suspenso', 'Suspenso'), ('inativo', 'Inativo')], default='ativo', max_length=20)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('logradouro', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('bairro', models.CharField(blank=True, max_length=150)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('complemento', models.CharField(blank=True, max_length=150)),
                ('login_pppoe', models.CharField(blank=True, max_length=100, verbose_name='Login PPPoE')),
                ('senha_pppoe', models.CharField(blank=True, max_length=100, verbose_name='Senha PPPoE')),
                ('data_ativacao', models.DateField(blank=True, null=True)),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=10)),
                ('porta', models.CharField(blank=True, max_length=10)),
                ('propriedade_equipamento', models.CharField(choices=[('empresa', 'Empresa'), ('cliente', 'Cliente')], default='empresa', max_length=20)),
                ('tipo_equipamento', models.CharField(choices=[('onu', 'ONU'), ('roteador', 'Roteador'), ('onu_roteador', 'ONU + Roteador'), ('ont', 'ONT')], default='onu_roteador', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('agendado', 'Agendado'), ('pago', 'Pago')], default='pendente', max_length=20)),
            ],
            options={
                'verbose_name': 'Conta a pagar',
                'verbose_name_plural': 'Contas a pagar',
                'ordering': ['vencimento'],
            },
        ),
        migrations.CreateModel(
            name='CTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('bairro', models.CharField(max_length=150)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('capacidade', models.PositiveIntegerField(choices=[(8, '8 portas'), (16, '16 portas')], default=16)),
                ('ruas_atendidas', models.TextField(blank=True, help_text='Uma rua por linha. Ex: Rua Clara\\nRua Puebla', verbose_name='Ruas atendidas')),
            ],
            options={
                'verbose_name': 'CTO',
                'verbose_name_plural': 'CTOs',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('velocidade_mb', models.PositiveIntegerField(help_text='Velocidade em Mega, ex: 300')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['velocidade_mb'],
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sem_sinal', 'Sem sinal'), ('lentidao', 'Lentidão'), ('instalacao', 'Instalação nova'), ('equipamento', 'Troca de equipamento'), ('financeiro', 'Financeiro'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('prioridade', models.CharField(choices=[('extrema', 'Extrema'), ('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=10)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('descricao', models.TextField(blank=True, verbose_name='Observação (do operador)')),
                ('observacao_fechamento', models.TextField(blank=True, verbose_name='Observação de fechamento (do técnico)')),
                ('pego_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('eh_retorno', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('finalizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_finalizados_por_mim', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados', to=settings.AUTH_USER_MODEL)),
                ('tecnico_ultimo_atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_retorno_anteriores', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='core.cliente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ChamadoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='chamados/%Y/%m/')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.chamado')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='cto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='core.cto'),
        ),
        migrations.CreateModel(
            name='LogAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255)),
                ('detalhes', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de atividade',
                'verbose_name_plural': 'Histórico de movimentações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='plano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='core.plano'),
        ),
    ]
