# Generated by Django 5.2.8 on 2026-07-26 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('drop', 'Bobina de Drop'), ('utp', 'Cabo UTP'), ('conector', 'Conector de Campo'), ('fibra', 'Fibra Óptica (AS)'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('unidade_medida', models.CharField(choices=[('un', 'Unidade'), ('m', 'Metros'), ('cx', 'Caixa'), ('rolo', 'Rolo')], default='un', max_length=10)),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Avisa quando o saldo ficar igual ou abaixo deste valor (deixe 0 pra não avisar)', max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais (Estoque)',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (Compra)'), ('saida', 'Saída (Retirada)')], max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(blank=True, help_text='Chamado relacionado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais_usados', to='core.chamado')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='core.material')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(blank=True, help_text='Pra quem o material foi liberado (só faz sentido em Retirada)', limit_choices_to={'role': 'tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais_retirados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação de estoque',
                'verbose_name_plural': 'Movimentações de estoque',
                'ordering': ['-criado_em'],
            },
        ),
    ]
