# Generated by Django 5.2.8 on 2026-07-26 16:11

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_material_movimentacaoestoque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seg_sex_entrada', models.TimeField(default=datetime.time(8, 0), verbose_name='Entrada (seg a sex)')),
                ('seg_sex_saida_almoco', models.TimeField(default=datetime.time(12, 0), verbose_name='Saída para almoço')),
                ('seg_sex_volta_almoco', models.TimeField(default=datetime.time(14, 0), verbose_name='Volta do almoço')),
                ('seg_sex_saida', models.TimeField(default=datetime.time(18, 0), verbose_name='Saída (seg a sex)')),
                ('sabado_ativo', models.BooleanField(default=True, verbose_name='Trabalha aos sábados?')),
                ('sabado_entrada', models.TimeField(default=datetime.time(8, 0), verbose_name='Entrada (sábado)')),
                ('sabado_saida', models.TimeField(default=datetime.time(12, 0), verbose_name='Saída (sábado)')),
                ('tolerancia_minutos', models.PositiveIntegerField(default=10, help_text='Quantos minutos de atraso ainda não contam como atraso', verbose_name='Tolerância (minutos)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jornada', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jornada de trabalho',
                'verbose_name_plural': 'Jornadas de trabalho',
            },
        ),
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida_almoco', 'Saída para almoço'), ('volta_almoco', 'Volta do almoço'), ('saida', 'Saída')], max_length=20)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('liberado_mais_cedo', models.BooleanField(default=False, help_text='Marcado quando o Administrador autoriza uma saída/registro fora do horário normal')),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ponto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de ponto',
                'verbose_name_plural': 'Registros de ponto',
                'ordering': ['-data_hora'],
            },
        ),
    ]
