# Generated by Django 5.2.8 on 2026-07-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_abonoponto'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonoponto',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='atestados/%Y/%m/', verbose_name='Atestado (PDF ou imagem)'),
        ),
    ]
