# Generated by Django 5.2.8 on 2026-07-26 18:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_abonoponto_anexo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiberacaoExtraPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('usada', models.BooleanField(default=False)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liberacoes_extra_ponto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liberação extra de ponto',
                'verbose_name_plural': 'Liberações extras de ponto',
                'ordering': ['-criado_em'],
            },
        ),
    ]
