# Generated by Django 5.2.8 on 2026-07-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_liberacaoextraponto'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroponto',
            name='eh_chamada_de_volta',
            field=models.BooleanField(default=False, help_text="Marcado quando essa entrada é de um 'chamado de volta' do Administrador (emergência), depois de já ter saído no dia"),
        ),
    ]
