# Generated by Django 5.2.8 on 2026-07-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_registroponto_eh_chamada_de_volta'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='atendimento_iniciado_em',
            field=models.DateTimeField(blank=True, help_text="Quando o técnico bateu a foto e apertou 'Iniciar Atendimento' (chegada no cliente)", null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='foto_inicio',
            field=models.ImageField(blank=True, null=True, upload_to='chamados/inicio/%Y/%m/', verbose_name='Foto de início (obrigatória)'),
        ),
    ]
