# Generated by Django 5.2.8 on 2026-07-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bloqueado_ate',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tentativas_login_falhas',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
