from django.urls import path
from . import views
from . import portal_views
from . import mikrotik_views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),

    # ---- Integração com Mikrotik ----
    path("mikrotik/configuracao/", mikrotik_views.configuracao_mikrotik_editar, name="configuracao_mikrotik_editar"),
    path("clientes/<int:pk>/mikrotik/sincronizar/", mikrotik_views.cliente_mikrotik_sincronizar, name="cliente_mikrotik_sincronizar"),
    path("clientes/<int:pk>/mikrotik/bloquear/", mikrotik_views.cliente_mikrotik_bloquear, name="cliente_mikrotik_bloquear"),
    path("clientes/<int:pk>/mikrotik/liberar/", mikrotik_views.cliente_mikrotik_liberar, name="cliente_mikrotik_liberar"),

    # ---- Portal do Cliente (área pública) ----
    path("portal/", portal_views.portal_login, name="portal_login"),
    path("portal/sair/", portal_views.portal_logout, name="portal_logout"),
    path("portal/primeiro-acesso/", portal_views.portal_primeiro_acesso, name="portal_primeiro_acesso"),
    path("portal/esqueci-senha/", portal_views.portal_esqueci_senha, name="portal_esqueci_senha"),
    path("portal/definir-senha/", portal_views.portal_definir_senha, name="portal_definir_senha"),
    path("portal/inicio/", portal_views.portal_dashboard, name="portal_dashboard"),
    path("portal/fatura/pdf/", portal_views.portal_segunda_via_pdf, name="portal_segunda_via_pdf"),
    path("portal/pedir-liberacao/", portal_views.portal_pedir_liberacao, name="portal_pedir_liberacao"),

    # ---- Administração do Portal (Promoções e Configuração) — só Admin ----
    path("promocoes/", portal_views.promocao_list, name="promocao_list"),
    path("promocoes/nova/", portal_views.promocao_create, name="promocao_create"),
    path("promocoes/<int:pk>/ativar-desativar/", portal_views.promocao_toggle, name="promocao_toggle"),
    path("promocoes/<int:pk>/excluir/", portal_views.promocao_delete, name="promocao_delete"),
    path("portal/configuracao/", portal_views.configuracao_empresa_editar, name="configuracao_empresa_editar"),
    path("licenca/", portal_views.licenca_editar, name="licenca_editar"),
    path("portal/solicitacoes-liberacao/", portal_views.solicitacao_liberacao_list, name="solicitacao_liberacao_list"),
    path("portal/solicitacoes-liberacao/<int:pk>/atender/", portal_views.solicitacao_liberacao_atender, name="solicitacao_liberacao_atender"),

    path("clientes/", views.ClienteListView.as_view(), name="cliente_list"),
    path("clientes/buscar-json/", views.cliente_busca_json, name="cliente_busca_json"),
    path("clientes/<int:pk>/verificar-retorno/", views.cliente_verificar_retorno, name="cliente_verificar_retorno"),
    path("clientes/<int:pk>/historico/", views.cliente_historico, name="cliente_historico"),
    path("clientes/novo/", views.ClienteCreateView.as_view(), name="cliente_create"),
    path("clientes/<int:pk>/editar/", views.ClienteUpdateView.as_view(), name="cliente_update"),
    path("clientes/<int:pk>/excluir/", views.cliente_delete, name="cliente_delete"),
    path("clientes/<int:pk>/cancelar/", views.cliente_cancelar, name="cliente_cancelar"),
    path("clientes/cancelados/", views.ClienteCanceladosListView.as_view(), name="cliente_cancelados"),
    path("clientes/exportar/excel/", views.cliente_export_excel, name="cliente_export_excel"),
    path("clientes/exportar/pdf/", views.cliente_export_pdf, name="cliente_export_pdf"),

    path("ctos/", views.CTOListView.as_view(), name="cto_list"),
    path("ctos/nova/", views.CTOCreateView.as_view(), name="cto_create"),
    path("ctos/exportar/excel/", views.cto_export_excel, name="cto_export_excel"),
    path("ctos/exportar/pdf/", views.cto_export_pdf, name="cto_export_pdf"),
    path("ctos/<int:pk>/", views.CTODetailView.as_view(), name="cto_detail"),
    path("ctos/<int:pk>/editar/", views.CTOUpdateView.as_view(), name="cto_update"),
    path("ctos/<int:pk>/portas-livres/", views.cto_portas_livres, name="cto_portas_livres"),

    path("planos/", views.PlanoListView.as_view(), name="plano_list"),
    path("planos/novo/", views.PlanoCreateView.as_view(), name="plano_create"),
    path("planos/<int:pk>/editar/", views.PlanoUpdateView.as_view(), name="plano_update"),
    path("planos/<int:pk>/excluir/", views.plano_delete, name="plano_delete"),

    path("chamados/", views.ChamadoListView.as_view(), name="chamado_list"),
    path("chamados/finalizados/", views.ChamadoFinalizadosListView.as_view(), name="chamado_finalizados"),
    path("chamados/relatorio-tempo/", views.relatorio_tempo_atendimento, name="relatorio_tempo_atendimento"),
    path("chamados/relatorio-tempo/pdf/", views.relatorio_tempo_atendimento_pdf, name="relatorio_tempo_atendimento_pdf"),
    path("chamados/novo/", views.ChamadoCreateView.as_view(), name="chamado_create"),
    path("chamados/<int:pk>/reatribuir/", views.reatribuir_chamado, name="reatribuir_chamado"),
    path("chamados/<int:pk>/prioridade/", views.alterar_prioridade_chamado, name="alterar_prioridade_chamado"),
    path("chamados/<int:pk>/cancelar/", views.cancelar_chamado, name="cancelar_chamado"),
    path("chamados/<int:pk>/voltar-aberto/", views.voltar_chamado_aberto, name="voltar_chamado_aberto"),
    path("chamados/<int:pk>/finalizar-operador/", views.finalizar_chamado_operador, name="finalizar_chamado_operador"),

    path("meus-chamados/", views.meus_chamados, name="meus_chamados"),
    path("chamados-disponiveis/", views.chamados_disponiveis, name="chamados_disponiveis"),
    path("chamados-disponiveis/<int:pk>/pegar/", views.pegar_chamado, name="pegar_chamado"),
    path("meus-chamados/<int:pk>/avancar/", views.avancar_chamado, name="avancar_chamado"),
    path("meus-chamados/<int:pk>/cliente-ausente/", views.chamado_cliente_ausente, name="chamado_cliente_ausente"),
    path("meus-chamados/<int:pk>/finalizar/", views.finalizar_chamado, name="finalizar_chamado"),

    path("financeiro/", views.financeiro, name="financeiro"),
    path("financeiro/inadimplentes/", views.clientes_inadimplentes_view, name="clientes_inadimplentes"),
    path("financeiro/contas-pagar/", views.contas_pagar_view, name="contas_pagar"),
    path("financeiro/contas-pagas/", views.contas_pagas_view, name="contas_pagas"),
    path("financeiro/debitos-congelados/", views.debitos_congelados_list, name="debitos_congelados"),
    path("financeiro/debitos-congelados/novo/", views.debito_congelado_create, name="debito_congelado_create"),
    path("financeiro/debitos-congelados/<int:pk>/negociar/", views.debito_congelado_negociar, name="debito_congelado_negociar"),
    path("financeiro/debitos-congelados/<int:pk>/excluir/", views.debito_congelado_delete, name="debito_congelado_delete"),
    path("financeiro/contas-pagar/nova/", views.conta_pagar_create, name="conta_pagar_create"),
    path("financeiro/contas-pagar/<int:pk>/editar/", views.conta_pagar_update, name="conta_pagar_update"),
    path("financeiro/contas-pagar/<int:pk>/excluir/", views.conta_pagar_delete, name="conta_pagar_delete"),
    path("financeiro/contas-pagar/<int:pk>/pagar/", views.conta_pagar_marcar_pago, name="conta_pagar_marcar_pago"),
    path("financeiro/contas-pagar/<int:pk>/desfazer/", views.conta_pagar_desmarcar_pago, name="conta_pagar_desmarcar_pago"),
    path("financeiro/clientes/<int:pk>/pagar/", views.registrar_pagamento, name="registrar_pagamento"),
    path("financeiro/exportar/excel/", views.financeiro_export_excel, name="financeiro_export_excel"),
    path("financeiro/exportar/pdf/", views.financeiro_export_pdf, name="financeiro_export_pdf"),

    path("relatorios/tecnicos/", views.relatorio_tecnicos, name="relatorio_tecnicos"),
    path("relatorios/", views.relatorios_view, name="relatorios"),
    path("relatorios/pdf/", views.relatorios_pdf, name="relatorios_pdf"),
    path("backup/", views.backup_view, name="backup_view"),
    path("backup/criar/", views.backup_criar_agora, name="backup_criar_agora"),
    path("backup/baixar/<str:nome>/", views.backup_download, name="backup_download"),
    path("backup/restaurar/<str:nome>/", views.backup_restaurar, name="backup_restaurar"),
    path("backup/enviar-restaurar/", views.backup_upload_restaurar, name="backup_upload_restaurar"),

    path("estoque/", views.MaterialListView.as_view(), name="material_list"),
    path("estoque/novo/", views.MaterialCreateView.as_view(), name="material_create"),
    path("estoque/<int:pk>/editar/", views.MaterialUpdateView.as_view(), name="material_update"),
    path("estoque/entrada/", views.estoque_entrada, name="estoque_entrada"),
    path("estoque/saida/", views.estoque_saida, name="estoque_saida"),
    path("estoque/historico/", views.estoque_historico, name="estoque_historico"),
    path("ponto/", views.ponto_bater, name="ponto_bater"),
    path("ponto/historico/", views.ponto_meu_historico, name="ponto_meu_historico"),
    path("ponto/admin/", views.ponto_admin_painel, name="ponto_admin_painel"),
    path("ponto/admin/liberar/", views.ponto_liberar_mais_cedo, name="ponto_liberar_mais_cedo"),
    path("ponto/admin/liberar-acesso/", views.ponto_liberar_acesso_extra, name="ponto_liberar_acesso_extra"),
    path("ponto/admin/abonar/", views.abono_criar, name="abono_criar"),
    path("ponto/admin/relatorio/", views.ponto_relatorio, name="ponto_relatorio"),
    path("ponto/admin/acumulado/", views.ponto_acumulado, name="ponto_acumulado"),
    path("ponto/admin/relatorio/pdf/", views.ponto_relatorio_pdf, name="ponto_relatorio_pdf"),
    path("ponto/admin/jornada/<int:usuario_id>/", views.jornada_editar, name="jornada_editar"),
    path("usuarios/", views.UsuarioListView.as_view(), name="usuario_list"),
    path("usuarios/novo/", views.UsuarioCreateView.as_view(), name="usuario_create"),
    path("usuarios/<int:pk>/editar/", views.UsuarioUpdateView.as_view(), name="usuario_update"),
    path("usuarios/<int:pk>/excluir/", views.usuario_delete, name="usuario_delete"),

    path("grupos-permissoes/", views.grupos_permissoes, name="grupos_permissoes"),
]
