# Generated by Django 5.2.5 on 2026-06-30 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0007_alter_historicomovimentacao_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField()),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ABERTO', 'Em Aberto'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(blank=True, max_length=30)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-vencimento'],
            },
        ),
    ]
