# Generated by Django 5.2.5 on 2026-06-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoInternet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Plano')),
                ('velocidade', models.CharField(max_length=50, verbose_name='Velocidade')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mensal')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Plano de Internet',
                'verbose_name_plural': 'Planos de Internet',
                'ordering': ['valor', 'nome'],
            },
        ),
    ]
