# Generated by Django 6.0.5 on 2026-06-08 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ctos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(max_length=250)),
                ('porta', models.IntegerField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctos.cto')),
            ],
        ),
    ]
