# Generated by Django 5.2.5 on 2026-06-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_data_cadastro_remove_cliente_endereco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('cliente_nome', models.CharField(max_length=100)),
                ('cto_nome', models.CharField(max_length=100)),
                ('porta', models.IntegerField()),
                ('acao', models.CharField(max_length=50)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
