# Generated by Django 5.2.5 on 2026-06-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_historicomovimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicomovimentacao',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
