# Generated by Django 5.2.5 on 2026-06-29 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_bairro_cliente_cep_cliente_cidade_and_more'),
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dia_vencimento',
            field=models.IntegerField(blank=True, choices=[(5, '05'), (10, '10'), (15, '15'), (20, '20')], null=True, verbose_name='Dia do Vencimento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planos.planointernet', verbose_name='Plano'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='valor_mensalidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Mensalidade'),
        ),
    ]
