# Generated by Django 5.2.5 on 2026-06-30 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_dia_vencimento_cliente_plano_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicomovimentacao',
            options={'ordering': ['-data'], 'verbose_name': 'Histórico', 'verbose_name_plural': 'Histórico de Movimentações'},
        ),
    ]
