# Generated by Django 5.2.5 on 2026-06-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_historicomovimentacao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_ativacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Ativação'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo em Dia'), ('SUSPENSO', 'Suspenso por Falta de Pagamento')], default='ATIVO', max_length=15, verbose_name='Situação'),
        ),
    ]
